stages:
  - mavenbuild
  - maventest
  - mavenDeploy
  - androidbuild
  - androidtest

maven-build:
  stage: mavenbuild
  tags:
    - spring_main
  script:
    - cd Backend/clue_backend
    - mvn package
  only:
    refs:
      - main
      - merge_requests
    changes:
      - Backend/clue_backend

maven-test:
  stage: maventest
  tags:
    - spring_main
  script:
    - cd Backend/clue_backend
    - mvn test
  artifacts:
    paths:
      - Backend/target/*.jar
  only:
    refs:
      - main
      - merge_requests
    changes:
      - Backend/clue_backend

autoDeploy:
  stage: mavenDeploy
  tags:
    - spring_main
  script:
    - cd Backend/clue_backend
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only:
    refs:
      - main
      - merge_requests
    changes:
      - Backend/clue_backend/*

android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  tags:
    - android_main
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Clue_Frontend/gradlew
  script:
    - cd Clue_Frontend
    - ./gradlew build
  artifacts:
    paths:
      - Clue_Frontend/app/build/outputs/
  only:
    refs:
      - main
      - merge_requests
    changes:
      - Clue_Frontend/*

android-test:
  image: gjandres/android-ci:latest
  stage: androidtest
  tags:
    - android_main
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Clue_Frontend/gradlew
  script:
    - cd Clue_Frontend
    - ./gradlew test
  only:
    refs:
      - main
      - merge_requests
    changes:
      - Clue_Frontend/*

