stages:          
  - build
  # - test
  # - deploy

build-job:
  stage: build
  tags:
    -springboot
  script:
    -cd Backend/clue_backend
    -mvn package
  
# test-job:
#   stage: test
#   tags:
#     -springboot
#   script: 