stages:
  - androidbuild
  - androidtest

android-build:
  stage: androidbuild
  tags:
    - Piper_tag
  before_script:
      - export GRADLE_USER_HOME=`pwd`/.gradle
      - chmod +x ./Clue_Frontend/gradlew
      script:
        - cd Clue_Frontend # to where you have ‘gradlew’
        - ./gradlew build
      artifacts:
        paths:
          - Clue_Frontend/app/build/outputs/
