stages:
  - androidbuild
  - androidtest

android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  tags:
    - Emily_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Clue_Frontend/gradlew
  script:
    - cd Clue_Frontend # to where you have ‘gradlew’
    - ./gradlew build
  artifacts:
    paths:
      - Clue_Frontend/app/build/outputs/

android-test:
  image: gjandres/android-ci:latest
  stage: androidtest
  tags:
    - Emily_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Clue_Frontend/gradlew
  script:
    - cd Clue_Frontend
    - ./gradlew test


